defaults:
  - _self_
  - components@models.modules.generator: generator
  - components@models.modules.discriminator: discriminator
  - components@models.modules.mapping_network: mapping_network
  - components@models.modules.style_encoder: style_encoder

_target_: src.models.star_gan_v2_module.StarGanV2LitModule

latent_dim: ${..latent_dim}
n_domains: ${..n_domains}
models:
  _target_: torch.nn.ModuleDict

optimizers:
  _target_: munch.Munch
  generator:
    _target_: torch.optim.Adam
    _partial_: True
    betas: [0, 0.99]
    lr: 1e-4
    weight_decay: 1e-4
  discriminator:
    _target_: torch.optim.Adam
    _partial_: True
    betas: [ 0, 0.99 ]
    lr: 1e-4
    weight_decay: 1e-4
  mapping_network:
    _target_: torch.optim.Adam
    _partial_: True
    betas: [ 0, 0.99 ]
    lr: 1e-6
    weight_decay: 1e-4
  style_encoder:
    _target_: torch.optim.Adam
    _partial_: True
    betas: [ 0, 0.99 ]
    lr: 1e-4
    weight_decay: 1e-4

gen_criterion:
  _target_: src.losses.common_losses.ConcatLoss
  losses:
    - ${....losses.AdversarialLoss}
    - ${....losses.StyleReconstructionLoss}
    - ${....losses.StyleDiversificationLoss}
    - ${....losses.CycleLoss}
  weights:
    - 1
    - 1
    - -1
    - 5

disc_criterion:
  _target_: src.losses.common_losses.ConcatLoss
  losses:
    - ${....losses.AdversarialLoss}
    - ${....losses.R1RegularizationLoss}
  weights:
    - 1
    - 1
