AdversarialLoss:
  _target_: src.losses.AdversarialLoss


StyleReconstructionLoss:
  _target_: src.losses.StyleReconstructionLoss


StyleDiversificationLoss:
  _target_: src.losses.StyleDiversificationLoss


CycleLoss:
  _target_: src.losses.CycleLoss


R1RegularizationLoss:
  _target_: src.losses.R1RegularizationLoss
